// Renders the dashboard from window.DATA (generated by scripts/clean.py).
// Every metric comes from DATA. A few framing words ("twice", the section headings) are
// written by hand and should be re-checked if the data changes.
// Tables and text render first; charts render last and only if Chart.js loaded,
// so a missing chart library can never blank the rest of the page.
(function () {
  const D = window.DATA;
  const K = D.kpis;
  const I = D.insights;
  const $ = (id) => document.getElementById(id);

  // ---------- formatting helpers ----------
  const num = (n) => n.toLocaleString("en-US");
  const money = (n) => {
    if (n == null) return "–";
    const a = Math.abs(n);
    if (a >= 1e6) return "$" + (n / 1e6).toFixed(2) + "M";
    if (a >= 1e3) return "$" + (n / 1e3).toFixed(a < 1e4 ? 1 : 0) + "K";
    return "$" + Math.round(n);
  };
  const pct = (n, d = 1) => (n == null ? "–" : n.toFixed(d) + "%");
  const pv = (p) => (p < 0.001 ? "p < 0.001" : `p = ${p}`); // p-values arrive at 2 significant figures
  const WORDS = ["no", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"];
  const words = (n) => WORDS[n] || num(n);
  const plural = (n, one, many) => `${words(n)} ${n === 1 ? one : many}`;
  const list = (xs) => (xs.length < 2 ? xs.join("") : xs.slice(0, -1).join(", ") + " and " + xs[xs.length - 1]);
  const ch = (name) => D.channels.find((c) => c.name === name);
  const src = (name) => D.sources.find((s) => s.name === name);
  const qLabel = (q) => q.replace(/(\d{4})Q(\d)/, "Q$2 ’$1").replace(/’20/, "’");
  const nFixed = D.corrected_amounts.length;

  // ---------- header ----------
  $("header-sub").innerHTML =
    `${num(D.meta.rows_clean)} leads created ${D.meta.lead_start}–${D.meta.lead_end}, followed through to closed deals. ` +
    `The raw CRM export needed cleanup first: duplicates, inconsistent labels, and ${words(nFixed)} deal amounts entered 100× too high. ` +
    `<a href="#data-notes">See what changed</a> and <a href="#crm-fixes">what I'd fix in the CRM</a>.`;
  $("asof").innerHTML = [
    `Deal outcomes as of <b>${D.meta.last_close}</b>`,
    `Pipeline activity through <b>${D.meta.last_activity}</b>`,
    `Single-touch attribution (the lead's campaign)`,
    `No spend data`,
  ].map((s) => `<li>${s}</li>`).join("");

  // ---------- KPI tiles ----------
  const mkt = src("Marketing programs");
  const P = D.pipeline;
  const kpis = [
    { label: "Leads created", value: num(K.leads), note: `${D.meta.lead_start} – ${D.meta.lead_end} · ${pct(K.mql_rate, 0)} became MQL` },
    { label: "Opportunities", value: num(K.opps), note: `${pct(K.lead_to_opp)} of leads · ${money(K.pipeline_created)} pipeline created` },
    { label: "Closed-won revenue", value: money(K.revenue), note: `${K.won} deals · avg ${money(K.avg_deal)} (${D.meta.priced_wins} with amounts)` },
    { label: "Win rate", value: pct(K.win_rate, 0), note: `${K.won} won / ${K.lost} lost · median ${D.meta.sales_cycle_median_days} days opp → close` },
    { label: "Marketing share of revenue", value: pct(mkt.share_revenue, 0), note: `and ${pct(mkt.share_pipeline, 0)} of pipeline created; the rest is referral and SDR` },
    { label: "Open pipeline", value: money(K.open_pipeline), note: `${K.open} open deals · ${P.past_due_at_last_activity_deals} of them (${money(P.past_due_at_last_activity_amount)}) past expected close` },
  ];
  $("kpis").innerHTML = kpis
    .map((k) => `<div class="card kpi"><div class="label">${k.label}</div><div class="value">${k.value}</div><div class="note">${k.note}</div></div>`)
    .join("");

  // ---------- takeaways ----------
  const ref = ch("Referral"), R = I.referral, E = I.events, W = I.weak, PS = I.paid_search, G = I.growth;
  const h0 = D.halves["2025 H1"], h2 = D.halves["2026 H1"];
  const WS = W.stages, WO = W.stages_other_marketing;
  const S = I.stalled;
  // Plain-language evidence tags for the takeaway cards; the p-value stays in the hover text.
  const evidence = (p, test) => {
    const [cls, label] = p < 0.01 ? ["solid", "Solid evidence"] : p < 0.1 ? ["borderline", "Borderline evidence"] : ["chance", "Could be chance"];
    return `<span class="tag ${cls}" title="${test}, ${pv(p)}">${label}</span>`;
  };
  $("headline").textContent =
    `Referrals and events convert best. ${list(W.channels)} bring ${pct(W.share_leads, 0)} of leads and ${plural(W.won, "won deal", "won deals")}.`;
  const takeaways = [
    {
      title: `Referrals are ${pct(ref.share_leads)} of leads but ${pct(ref.share_revenue, 0)} of revenue`,
      tag: evidence(R.lead_to_opp_p, "Referral lead → opportunity rate vs all other leads (Fisher exact)"),
      body: `${pct(ref.lead_to_opp, 0)} of referral leads become opportunities, against ${pct(R.lead_to_opp_rest, 0)} of all other leads. ` +
            `Each referral lead is worth ${money(ref.rev_per_lead)} in closed-won revenue, about ${R.rev_per_lead_multiple}× the average lead. ` +
            `The edge is in conversion, not closing: referral deals win ${pct(ref.win_rate, 0)} of the time against ${pct(R.win_rate_rest, 0)} for everything else, a gap too small to rule out chance. ` +
            `Revenue is also understated: ${words(R.unpriced_wins)} of the ${words(R.unpriced_wins_total)} won deals with no amount recorded are referrals.`,
      so: `Referral is the highest-yield source per lead. Whether it's the best place for the next dollar depends on what the program costs, which this export doesn't include, and on how many more referrals customers and partners can realistically produce.`,
    },
    {
      title: `Events turn leads into opportunities at twice the rate of other leads`,
      tag: evidence(E.lead_to_opp_p, "Event lead → opportunity rate vs all other leads (Fisher exact)"),
      body: `Events are ${pct(E.share_leads)} of leads and ${pct(E.share_revenue, 0)} of revenue. ${pct(E.lead_to_opp)} of event leads become opportunities, against ${pct(E.lead_to_opp_rest)} for all other leads, ` +
            `and that holds for all ${words(E.programs)} event programs (${E.program_lead_to_opp_range[0].toFixed(1)}–${pct(E.program_lead_to_opp_range[1])}). ` +
            `They produce ${E.won_per_100.toFixed(1)} won deals per 100 leads, against ${E.won_per_100_rest.toFixed(1)} elsewhere. ` +
            `As with referrals, the edge is in conversion: the ${pct(E.win_rate, 0)} win rate isn't reliably higher than the ${pct(E.win_rate_rest, 0)} elsewhere.`,
      so: `Events are the strongest source marketing fully controls. Whether to add more depends on cost per opportunity, which this export can't show; event spend is the first number to pull.`,
    },
    {
      title: `${list(W.channels)}: ${pct(W.share_leads, 0)} of leads, ${plural(W.won, "won deal", "won deals")}`,
      tag: evidence(W.lead_to_opp_p, "Lead → opportunity rate vs every other channel (Fisher exact)"),
      body: `${num(W.leads)} leads produced ${W.opps} opportunities (${pct(W.lead_to_opp)}, against ${pct(W.lead_to_opp_rest)} for every other channel) and ${plural(W.won, "won deal", "won deals")} worth ${money(W.revenue)}. ` +
            `They fall behind at every stage: ${pct(WS.mql_rate, 0)} become MQLs (${pct(WO.mql_rate, 0)} for other marketing programs), ${pct(WS.mql_to_sql, 0)} of those MQLs become SQLs (${pct(WO.mql_to_sql, 0)}), ` +
            `and ${pct(WS.sql_to_opp, 0)} of SQLs become opportunities (${pct(WO.sql_to_opp, 0)}). ` +
            `Their ${money(W.open_pipeline)} of open pipeline is mostly one ${money(W.largest_open)} ${W.largest_open_campaign} deal, still in ${W.largest_open_stage} after ${Math.round(W.largest_open_age_days / 30.4)} months.`,
      so: `There's no spend data, so ROI is unknown, but these channels are the first thing to check against budget. If they're meant to build awareness, judge them on that; as pipeline sources, they aren't working.`,
    },
    {
      title: `Leads grew ${G.lead_growth}%; opportunities from those leads grew ${G.opp_growth}%`,
      tag: evidence(G.p, "H1 2025 vs H1 2026 lead → opportunity rate (Fisher exact)"),
      body: `Leads created in H1 2026 vs H1 2025: ${num(h0.leads)} → ${num(h2.leads)}, and their opportunities ${h0.opps} → ${h2.opps}. ` +
            `Lead → opportunity was ${pct(h0.lead_to_opp)} in H1 2025 and ${G.later_quarters_range[0].toFixed(1)}–${pct(G.later_quarters_range[1])} in every quarter since. ` +
            `Channel mix didn't cause it: at H1 2025's channel rates, H1 2026's leads would have converted at ${pct(G.mix_expected)}. ` +
            `The MQL rate barely moved (${pct(h0.mql_rate, 0)} → ${pct(h2.mql_rate, 0)}). Against H1 2025's stage rates, H1 2026 came up about ${G.shortfall_total} opportunities short, mostly after MQL: ` +
            `about ${G.shortfall.at_sql_to_opp} at SQL → opportunity and ${G.shortfall.at_mql_to_sql} at MQL → SQL. ` +
            `The overall gap is borderline and neither stage stands out on its own, so treat it as a signal to check, not a proven decline.`,
      so: `Before setting the next lead-volume target, review both handoffs with Sales: which MQLs get accepted as SQLs, and why accepted SQLs don't become opportunities. ` +
          `${num(S.mql)} MQLs never got a recorded decision, and ${S.mql_unowned === S.mql ? "none of them" : `only ${num(S.mql - S.mql_unowned)} of them`} was ever assigned an owner.`,
    },
  ];
  $("takeaways").innerHTML = takeaways
    .map((t, i) => `<div class="card take"><div class="num">${i + 1}</div><div><h3>${t.title}</h3>${t.tag}<p>${t.body}</p><p class="so"><b>So what:</b> ${t.so}</p></div></div>`)
    .join("");

  const N = I.not_solid, T = N.tests;
  const web = ch("Webinar");
  const regions = [...D.segments.Region].sort((a, b) => a.win_rate - b.win_rate);
  const rLo = regions[0], rHi = regions[regions.length - 1];
  const thin = [...D.segments.Region].sort((a, b) => a.won + a.lost - (b.won + b.lost)).slice(0, 2);
  const thinText = list(thin.map((r) => `${r.name} (${r.won + r.lost})`));
  const atLeast = (p) => pv(p).replace("=", "≥");
  const caveats = [
    `<b>Webinar win rate.</b> Only ${N.webinar_won} of ${N.webinar_closed} closed webinar deals were won (${pct(web.win_rate, 0)}). Nearly all of the shortfall comes from leads created in H2 2025, which went ${N.webinar_h2_won} for ${N.webinar_h2_closed}; ` +
      `outside that window webinars won ${N.webinar_other_won} of ${N.webinar_other_closed} (${pct(N.webinar_other_win_rate, 0)}), against ${pct(N.rest_other_win_rate, 0)} for other channels over the same periods. ` +
      `I picked that window after looking at the data, so it's a lead for a deal review, not a budget decision.`,
    `<b>Paid Search, the largest lead source.</b> It supplies ${pct(PS.share_leads, 0)} of leads and wins ${PS.won_per_100.toFixed(1)} deals per 100 of them: level with Webinar (${web.won_per_100.toFixed(1)}), ` +
      `below Organic Search (${ch("Organic Search").won_per_100.toFixed(1)}) and Events (${ch("Events").won_per_100.toFixed(1)}). The ${PS.won_per_100_rest.toFixed(1)} average for all other leads is lifted by Referral (${ref.won_per_100.toFixed(1)}), and the gap to it could be chance (${pv(PS.won_per_100_p)}). ` +
      `Its #${PS.revenue_rank} revenue rank rests on ${words(PS.corrected_deals)} of the ${words(nFixed)} corrected deals; without them it would rank #${PS.revenue_rank_if_excluded}. Worth a campaign-level review once spend is known.`,
    `<b>Region and industry.</b> Industry shows no difference in conversion or win rate (${atLeast(Math.min(T.industry_lead_to_opp, T.industry_win_rate))}). ` +
      `Region shows none in conversion (${pv(T.region_lead_to_opp)}); win rates run from ${pct(rLo.win_rate, 0)} (${rLo.name}, ${rLo.won} of ${rLo.won + rLo.lost}) to ${pct(rHi.win_rate, 0)} (${rHi.name}, ${rHi.won} of ${rHi.won + rHi.lost}), ` +
      `a borderline spread (${pv(T.region_win_rate)}) resting on few closed deals in ${thinText}. Company size changes deal size, not whether a deal is won (${pv(T.company_size_win_rate)}).`,
    `<b>Sales reps.</b> Win rates across the ${words(N.reps)} reps range from ${N.rep_win_rate_range[0]}% to ${N.rep_win_rate_range[1]}%, which is within what chance produces on ${N.rep_closed_range[0]}–${N.rep_closed_range[1]} closed deals each (${pv(T.owner_win_rate)}).`,
  ];
  $("caveats").innerHTML = caveats.map((c) => `<li>${c}</li>`).join("");

  // ---------- source split ----------
  const srcColor = ["var(--src-1)", "var(--src-2)", "var(--src-3)"];
  const srcInk = ["#fff", "var(--ink)", "var(--ink)"];
  const ref2 = src("Customer & partner referral");
  $("sources-sub").innerHTML =
    `Marketing programs bring ${pct(mkt.share_leads, 0)} of leads but ${pct(mkt.share_revenue, 0)} of closed-won revenue. ` +
    `Customer and partner referrals bring ${pct(ref2.share_leads)} of leads and ${pct(ref2.share_revenue, 0)} of revenue. ` +
    `Counting referrals separately is a judgment call: referral programs are often run by marketing, but the lead comes from a customer or partner.`;
  $("sources-legend").innerHTML = D.sources.map((s, i) => `<span><i style="background:${srcColor[i]}"></i>${s.name}</span>`).join("");
  const stackRows = [
    { what: "Leads", sub: num(K.leads), key: "share_leads" },
    { what: "Pipeline created", sub: money(K.pipeline_created), key: "share_pipeline" },
    { what: "Closed-won revenue", sub: money(K.revenue), key: "share_revenue" },
  ];
  $("sources-stack").innerHTML = stackRows
    .map((r) => `<div class="stack-row"><div class="what">${r.what}<span>${r.sub}</span></div><div class="stack" role="img" aria-label="${r.what} by source: ${D.sources.map((s) => `${s.name} ${pct(s[r.key], 0)}`).join(", ")}">` +
      D.sources.map((s, i) => `<div class="seg" style="flex:${s[r.key]};background:${srcColor[i]};color:${srcInk[i]}" title="${s.name}: ${pct(s[r.key])}">${s[r.key] >= 9 ? pct(s[r.key], 0) : ""}</div>`).join("") +
      `</div></div>`)
    .join("");
  $("sourcesTable").innerHTML =
    `<thead><tr><th>Source</th><th>Leads</th><th>Lead → opp</th><th class="wide-only">Pipeline created</th><th>Closed-won revenue</th><th class="wide-only">Won / 100 leads</th><th>Revenue per lead</th></tr></thead><tbody>` +
    D.sources.map((s, i) => `<tr><td class="name"><span class="dot" style="background:${srcColor[i]}"></span>${s.name}</td><td>${num(s.leads)}</td><td>${pct(s.lead_to_opp)}</td>` +
      `<td class="wide-only">${money(s.pipeline_created)}</td><td>${money(s.revenue)}</td><td class="wide-only">${s.won_per_100.toFixed(1)}</td><td>${money(s.rev_per_lead)}</td></tr>`).join("") +
    `<tr class="tfoot"><td>All leads</td><td>${num(K.leads)}</td><td>${pct(K.lead_to_opp)}</td><td class="wide-only">${money(K.pipeline_created)}</td><td>${money(K.revenue)}</td><td class="wide-only">${K.won_per_100.toFixed(1)}</td><td>${money(K.rev_per_lead)}</td></tr></tbody>`;

  // ---------- funnel ----------
  const stalled = D.quality.find((q) => q.issue === "No outcome for leads that stall");
  $("funnel-sub").innerHTML =
    `Every lead created in the period, and how far it got. Percentages under each bar are stage-to-stage conversion. ` +
    `${num(stalled.count)} leads stopped at MQL or SQL and have no rejected or recycled status in the CRM.`;
  const ramp = ["#86b6ef", "#5598e7", "#2a78d6", "#1c5cab", "#104281"]; // ordinal blue, light → dark
  const top = D.funnel[0].n;
  let fHtml = "";
  D.funnel.forEach((s, i) => {
    if (i > 0) {
      const prev = D.funnel[i - 1];
      const label = i === D.funnel.length - 1
        ? `${pct((s.n / prev.n) * 100, 0)} of opportunities won so far (${pct(K.win_rate, 0)} of closed deals)`
        : `${pct((s.n / prev.n) * 100, 0)} converted`;
      fHtml += `<div class="funnel-row" style="padding:0"><div></div><div class="step">↓ ${label}</div><div></div></div>`;
    }
    fHtml += `<div class="funnel-row">
      <div class="stage">${s.stage}</div>
      <div class="bar-track"><div class="bar" style="width:${(s.n / top) * 100}%;background:${ramp[i]}"></div></div>
      <div class="count">${num(s.n)}<span>${i === 0 ? "all leads" : pct((s.n / top) * 100) + " of leads"}</span></div>
    </div>`;
  });
  $("funnel").innerHTML = fHtml;

  // ---------- tables ----------
  const cell = (r, key, text) => {
    const f = r.flags && r.flags[key];
    if (!f) return text;
    const word = f === "hi" ? "above" : "below";
    return `<span class="${f}" title="Significantly ${word} all other leads">${text}<span class="sr"> (significantly ${word} other leads)</span></span>`;
  };
  const winCell = (r) => `${cell(r, "win_rate", pct(r.win_rate, 0))}<span class="n">${r.won}/${r.won + r.lost}</span>`;
  const rplCell = (r, max, bar = true) =>
    `<span class="inbar">${bar ? `<span class="track"><span class="b" style="width:${Math.max(2, (r.rev_per_lead / max) * 100)}%"></span></span>` : ""}<span>${money(r.rev_per_lead)}</span></span>`;

  function scoreTable(rows, opts = {}) {
    const max = Math.max(...rows.map((r) => r.rev_per_lead));
    const head = `<thead><tr>
      <th>${opts.first || "Channel"}</th><th>Leads</th><th class="wide-only">MQL rate</th><th>Lead → opp</th><th>Won / 100 leads</th><th>Win rate</th>
      <th>Closed-won revenue</th><th class="wide-only">Avg deal</th><th class="wide-only">Open pipeline</th><th class="rpl">Revenue per lead</th></tr></thead>`;
    const body = rows.map((r) => `<tr>
      <td class="name">${r.name}${opts.sub ? `<span class="sub-name">${opts.sub(r)}</span>` : ""}</td>
      <td>${num(r.leads)}</td>
      <td class="wide-only">${cell(r, "mql_rate", pct(r.mql_rate, 0))}</td>
      <td>${cell(r, "lead_to_opp", pct(r.lead_to_opp))}</td>
      <td>${cell(r, "won_per_100", r.won_per_100.toFixed(1))}</td>
      <td>${winCell(r)}</td>
      <td>${money(r.revenue)}</td>
      <td class="wide-only">${money(r.avg_deal)}</td>
      <td class="wide-only">${money(r.open_pipeline)}</td>
      <td>${rplCell(r, max)}</td>
    </tr>`).join("");
    const foot = `<tr class="tfoot"><td>All leads</td><td>${num(K.leads)}</td><td class="wide-only">${pct(K.mql_rate, 0)}</td><td>${pct(K.lead_to_opp)}</td><td>${K.won_per_100.toFixed(1)}</td>
      <td>${pct(K.win_rate, 0)}<span class="n">${K.won}/${K.won + K.lost}</span></td><td>${money(K.revenue)}</td><td class="wide-only">${money(K.avg_deal)}</td><td class="wide-only">${money(K.open_pipeline)}</td><td>${money(K.rev_per_lead)}</td></tr>`;
    return head + `<tbody>${body}${foot}</tbody>`;
  }
  const sourceTag = (name) => (name === "Marketing programs" ? "" : name);
  $("channelTable").innerHTML = scoreTable(D.channels, { sub: (r) => sourceTag(r.source) });
  $("campaign-summary").textContent = `Show all ${D.campaigns.length} campaigns`;
  $("campaign-note").textContent =
    `Directional only. Within each channel, campaigns don't differ by more than chance on conversion or win rate (smallest ${pv(N.campaign_within_channel_min_p)}).`;
  $("campaignTable").innerHTML = scoreTable(D.campaigns, { first: "Campaign", sub: (r) => r.channel });

  // ---------- segments ----------
  const big = I.size.flagged[0];
  const sizes = D.segments["Company size"];
  const segCaptions = {
    "Company size":
      `Bigger companies buy much bigger deals (avg ${money(sizes[0].avg_deal)} at ${sizes[0].name} employees, ${money(sizes[sizes.length - 1].avg_deal)} at ${sizes[sizes.length - 1].name}) but don't win more often (${pv(T.company_size_win_rate)}).` +
      (big ? ` ${big.name}-employee companies convert to opportunities about ${(big.lead_to_opp / big.lead_to_opp_rest).toFixed(1)}× as often as everyone else (${pct(big.lead_to_opp)} vs ${pct(big.lead_to_opp_rest)}).` : ""),
    Region: `No regional difference in conversion is bigger than chance (${pv(T.region_lead_to_opp)}). Win rates vary more, but the extremes rest on few closed deals in ${thinText} (${pv(T.region_win_rate)}).`,
    Industry: `No industry difference in conversion or win rate is bigger than chance (${atLeast(Math.min(T.industry_lead_to_opp, T.industry_win_rate))}). Shown for completeness.`,
  };
  const segNames = Object.keys(D.segments);
  function segTable(name) {
    const rows = D.segments[name];
    const max = Math.max(...rows.map((r) => r.rev_per_lead));
    const bars = name === "Company size"; // the only cut with real differences; bars elsewhere would imply a ranking
    $("segCaption").textContent = segCaptions[name] || "";
    const head = `<thead><tr><th>${name}</th><th>Leads</th><th>Lead → opp</th><th>Win rate</th><th>Avg deal</th><th>Closed-won revenue</th><th class="rpl">Revenue per lead</th></tr></thead>`;
    const body = rows.map((r) => `<tr>
      <td class="name">${r.name}</td><td>${num(r.leads)}</td>
      <td>${cell(r, "lead_to_opp", pct(r.lead_to_opp))}</td>
      <td>${winCell(r)}</td>
      <td>${money(r.avg_deal)}</td><td>${money(r.revenue)}</td>
      <td>${rplCell(r, max, bars)}</td>
    </tr>`).join("");
    $("segTable").innerHTML = head + `<tbody>${body}</tbody>`;
    updateSwipeHints();
  }
  $("segTabs").innerHTML = segNames.map((n, i) => `<button type="button" aria-pressed="${i === 0}" aria-controls="segTable" data-seg="${n}">${n}</button>`).join("");
  $("segTabs").addEventListener("click", (e) => {
    const b = e.target.closest("button");
    if (!b) return;
    $("segTabs").querySelectorAll("button").forEach((x) => x.setAttribute("aria-pressed", x === b));
    segTable(b.dataset.seg);
  });

  // ---------- trend + pipeline notes ----------
  const partial = D.revenue_by_q.filter((r) => r.partial).map((r) => qLabel(r.q));
  const missing = G.expected_missing_opps < 1 ? "fewer than one June opportunity is" : `about ${Math.round(G.expected_missing_opps)} June opportunities are`;
  $("trend-note").innerHTML =
    `${list(partial)} revenue is incomplete: the export only contains leads created from ${D.meta.lead_start}, so deals from earlier leads that closed in those quarters are missing. ` +
    `The opportunity-rate trend is safe to read: opportunities are recorded through ${D.meta.last_activity}, ${G.runway_days} days after the last lead, and ${pct(G.share_opps_within_runway, 0)} of opportunities appear within ${G.runway_days} days of their lead, ` +
    `so ${missing} likely still missing. ` +
    `Single quarters are noisy: no two differ by more than chance (smallest ${pv(G.min_pair_p)}). The step down only shows when H1 2025 (${pct(h0.lead_to_opp)}) is compared with everything since (${pct(G.later_rate)}), and even that is borderline. ` +
    `Open pipeline: ${P.past_due_at_last_activity_deals} deals (${money(P.past_due_at_last_activity_amount)}) were expected to close by ${D.meta.last_activity} but hadn't, and no deal at all closed after ${D.meta.last_close}. ` +
    `Treat the expected close dates as forecasts to confirm with Sales.`;
  $("share-note").textContent =
    `Only the ends of this ranking are solid: Referral at the top, Paid Social and Content Syndication at the bottom. The channels in between are too close to rank.`;

  // ---------- CRM fixes ----------
  $("fixes").innerHTML = D.crm_fixes
    .map((f, i) => `<div class="card fix"><div class="num">${i + 1}</div><div><h3>${f.title}</h3><p class="owner">Owner: ${f.owner}</p>` +
      `<p>${f.problem}</p><p class="do">${f.fix}</p></div></div>`)
    .join("");

  // ---------- data notes ----------
  $("notes").innerHTML = D.quality
    .map((q) => `<div class="card note-item"><h3>${q.issue}${q.count != null ? `<span class="count">${num(q.count)} ${q.count === 1 ? "row" : "rows"} affected</span>` : ""}</h3>
      <div><p>${q.detail}</p><p class="action">${q.action}</p></div></div>`)
    .join("");
  $("amtTable").innerHTML =
    `<thead><tr><th>Opportunity</th><th>Company size</th><th>Amount in CRM</th><th>Corrected (÷100)</th><th>Median won deal, same size</th></tr></thead><tbody>` +
    D.corrected_amounts.map((r) => `<tr><td class="name">${r.opportunity_id}</td><td>${r.company_size}</td><td>${money(r.amount_raw)}</td><td>${money(r.deal_amount_usd)}</td><td>${money(r.won_median)}</td></tr>`).join("") +
    `<tr class="tfoot"><td colspan="2">Closed-won total</td><td>${money(D.raw_closed_won)}</td><td>${money(K.revenue)}</td><td></td></tr></tbody>`;

  // Show "swipe for more" only above tables that actually overflow at the current width.
  function updateSwipeHints() {
    document.querySelectorAll(".table-wrap").forEach((w) => {
      const hint = w.previousElementSibling;
      if (hint && hint.classList.contains("swipe")) hint.hidden = w.scrollWidth <= w.clientWidth + 1;
    });
  }
  segTable(segNames[0]);
  window.addEventListener("resize", updateSwipeHints);
  document.querySelectorAll("details").forEach((d) => d.addEventListener("toggle", updateSwipeHints));

  // ---------- charts (last, so nothing above depends on Chart.js) ----------
  const describe = (labels, vals, fmt) => labels.map((l, i) => `${l}: ${fmt(vals[i])}`).join("; ");
  const chs = [...D.channels].sort((a, b) => b.share_revenue - a.share_revenue);
  const qs = D.quarters.map((q) => qLabel(q.q));
  const rq = D.revenue_by_q;
  const pm = P.by_month;
  const monthLabel = (m) => m.replace(/ (\d{2})(\d{2})$/, " ’$2");
  const alt = {
    shareChart: "Share of leads vs share of closed-won revenue by channel. " + describe(chs.map((c) => c.name), chs, (c) => `${pct(c.share_leads)} of leads, ${pct(c.share_revenue)} of revenue`),
    leadsQ: "Leads created per quarter. " + describe(qs, D.quarters.map((q) => q.leads), num),
    convQ: "Lead to opportunity rate per quarter. " + describe(qs, D.quarters.map((q) => q.lead_to_opp), (v) => pct(v)),
    revQ: "Closed-won revenue per close quarter. " + describe(rq.map((r) => qLabel(r.q) + (r.partial ? " (partial)" : "")), rq.map((r) => r.revenue), money),
    pipeM: "Open pipeline by expected close month. " + describe(pm.map((m) => monthLabel(m.month)), pm, (m) => `${money(m.amount)}${m.overdue_amount ? `, ${money(m.overdue_amount)} already past due` : ""}`),
  };
  Object.entries(alt).forEach(([id, text]) => $(id).setAttribute("aria-label", text));
  if (!window.Chart) {
    Object.entries(alt).forEach(([id, text]) => $(id).insertAdjacentHTML("afterend", `<div class="chart-fallback">Chart unavailable. ${text}</div>`));
    return;
  }
  Chart.defaults.font.family = getComputedStyle(document.body).fontFamily;
  Chart.defaults.font.size = 12;
  Chart.defaults.color = "#6b6964";
  Chart.defaults.plugins.legend.display = false;
  Chart.defaults.plugins.tooltip.backgroundColor = "#0b0b0b";
  Chart.defaults.plugins.tooltip.padding = 10;
  Chart.defaults.plugins.tooltip.cornerRadius = 6;
  Chart.defaults.maintainAspectRatio = false;
  const grid = { color: "#e9e8e2", drawTicks: false };
  const noGrid = { display: false };
  const border = { color: "#c3c2b7" };
  const niceMax = (v, step) => Math.ceil((v * 1.1) / step) * step;
  const twoLine = (s) => s.split(" "); // "Q1 ’25" on two lines, so narrow screens don't collide

  // share of leads vs share of revenue
  const shareMax = niceMax(Math.max(...chs.map((c) => Math.max(c.share_leads, c.share_revenue))), 5);
  new Chart($("shareChart"), {
    type: "bar",
    data: {
      labels: chs.map((c) => (window.innerWidth < 500 && c.name.length > 12 ? c.name.split(" ") : c.name)),
      datasets: [
        { label: "Share of leads", data: chs.map((c) => c.share_leads), backgroundColor: "#8a887f", borderRadius: 4, borderSkipped: "start", barPercentage: 0.8, categoryPercentage: 0.7 },
        { label: "Share of closed-won revenue", data: chs.map((c) => c.share_revenue), backgroundColor: "#2a78d6", borderRadius: 4, borderSkipped: "start", barPercentage: 0.8, categoryPercentage: 0.7 },
      ],
    },
    options: {
      indexAxis: "y",
      scales: {
        x: { grid, border, ticks: { callback: (v) => v + "%", padding: 6, stepSize: 5, maxRotation: 0 }, max: shareMax },
        y: { grid: { display: false, drawTicks: false }, border, ticks: { color: "#0b0b0b", font: { size: 13 }, padding: 6 } },
      },
      plugins: {
        tooltip: {
          callbacks: {
            label: (ctx) => {
              const c = chs[ctx.dataIndex];
              return ctx.datasetIndex === 0
                ? ` Leads: ${pct(c.share_leads)} (${num(c.leads)})`
                : ` Revenue: ${pct(c.share_revenue)} (${money(c.revenue)})`;
            },
          },
        },
      },
    },
  });

  const smallOpts = (tickFmt, extra = {}, stacked = false) => ({
    scales: {
      x: { stacked, grid: noGrid, border, ticks: { padding: 4, maxRotation: 0, autoSkip: false, font: { size: 11 } } },
      y: { stacked, grid, border: { display: false }, beginAtZero: true, ticks: { callback: tickFmt, padding: 6, maxTicksLimit: 5 }, ...extra },
    },
  });
  new Chart($("leadsQ"), {
    type: "bar",
    data: { labels: qs.map(twoLine), datasets: [{ data: D.quarters.map((q) => q.leads), backgroundColor: "#2a78d6", borderRadius: 4, borderSkipped: "start", maxBarThickness: 36 }] },
    options: { ...smallOpts((v) => num(v)), plugins: { tooltip: { callbacks: { title: (c) => qs[c[0].dataIndex], label: (c) => ` ${num(c.raw)} leads · ${D.quarters[c.dataIndex].opps} became opportunities` } } } },
  });
  const rateMax = niceMax(Math.max(...D.quarters.map((q) => q.lead_to_opp)), 2);
  new Chart($("convQ"), {
    type: "line",
    data: { labels: qs.map(twoLine), datasets: [{ data: D.quarters.map((q) => q.lead_to_opp), borderColor: "#2a78d6", backgroundColor: "#2a78d6", borderWidth: 2, pointRadius: 4, pointHoverRadius: 6, pointBorderColor: "#fcfcfb", pointBorderWidth: 2, tension: 0 }] },
    options: { ...smallOpts((v) => v + "%", { max: rateMax }), interaction: { mode: "index", intersect: false }, plugins: { tooltip: { callbacks: { title: (c) => qs[c[0].dataIndex], label: (c) => ` ${pct(c.raw)} of leads became opportunities (${D.quarters[c.dataIndex].opps} of ${num(D.quarters[c.dataIndex].leads)})` } } } },
  });
  new Chart($("revQ"), {
    type: "bar",
    data: {
      labels: rq.map((r) => twoLine(qLabel(r.q) + (r.partial ? "*" : ""))),
      datasets: [{ data: rq.map((r) => r.revenue), backgroundColor: rq.map((r) => (r.partial ? "#b7d3f6" : "#2a78d6")), borderRadius: 4, borderSkipped: "start", maxBarThickness: 36 }],
    },
    options: {
      ...smallOpts((v) => money(v)),
      plugins: { tooltip: { callbacks: { title: (c) => qLabel(rq[c[0].dataIndex].q), label: (c) => ` ${money(c.raw)} from ${rq[c.dataIndex].deals} deals${rq[c.dataIndex].partial ? " (partial quarter)" : ""}` } } },
    },
  });
  new Chart($("pipeM"), {
    type: "bar",
    data: {
      labels: pm.map((m) => twoLine(monthLabel(m.month))),
      datasets: [
        { label: "Past expected close", data: pm.map((m) => m.overdue_amount), backgroundColor: "#b7d3f6", borderSkipped: "start", maxBarThickness: 36 },
        { label: "Still ahead", data: pm.map((m) => m.amount - m.overdue_amount), backgroundColor: "#2a78d6", borderRadius: { topLeft: 4, topRight: 4 }, borderSkipped: false, maxBarThickness: 36 },
      ],
    },
    options: {
      ...smallOpts((v) => money(v), {}, true),
      plugins: {
        tooltip: {
          callbacks: {
            title: (c) => monthLabel(pm[c[0].dataIndex].month),
            label: (c) => {
              const m = pm[c.dataIndex];
              return c.datasetIndex === 0
                ? ` Past expected close: ${money(m.overdue_amount)} (${plural(m.overdue_deals, "deal", "deals")})`
                : ` Still ahead: ${money(m.amount - m.overdue_amount)} (${plural(m.deals - m.overdue_deals, "deal", "deals")})`;
            },
          },
        },
      },
    },
  });
})();
