// Renders the dashboard from window.DATA (generated by scripts/clean.py).
// Every number on the page comes from DATA, so re-running the script updates the whole page.
(function () {
  const D = window.DATA;
  const K = D.kpis;
  const $ = (id) => document.getElementById(id);

  // ---------- formatting helpers ----------
  const num = (n) => n.toLocaleString("en-US");
  const money = (n) => {
    if (n == null) return "–";
    if (Math.abs(n) >= 1e6) return "$" + (n / 1e6).toFixed(2).replace(/\.?0+$/, "") + "M";
    if (Math.abs(n) >= 1e4) return "$" + Math.round(n / 1e3) + "K";
    return "$" + Math.round(n).toLocaleString("en-US");
  };
  const pct = (n, d = 1) => (n == null ? "–" : n.toFixed(d).replace(/\.0$/, "") + "%");
  const ch = (name) => D.channels.find((c) => c.name === name);

  // ---------- header ----------
  $("header-sub").innerHTML =
    `${num(D.meta.rows_clean)} leads created ${D.meta.lead_start}–${D.meta.lead_end}, followed through to closed deals ` +
    `(outcomes through ${D.meta.last_close}). The raw CRM export needed cleanup first: duplicates, inconsistent labels, and six deal ` +
    `amounts that were 100× too high. <a href="#data-notes">See what changed</a>.`;

  // ---------- KPI tiles ----------
  const kpis = [
    { label: "Leads created", value: num(K.leads), note: `${D.meta.lead_start} – ${D.meta.lead_end}` },
    { label: "Became MQL", value: pct(K.mql_rate, 0), note: `${num(K.mql)} MQLs · ${num(K.sql)} SQLs` },
    { label: "Opportunities", value: num(K.opps), note: `${pct(K.lead_to_opp)} of leads · ${money(K.pipeline_created)} created` },
    { label: "Closed-won revenue", value: money(K.revenue), note: `${K.won} deals · avg ${money(K.avg_deal)}` },
    { label: "Win rate", value: pct(K.win_rate, 0), note: `${K.won} won / ${K.lost} lost · ${D.meta.sales_cycle_median_days}-day median cycle` },
    { label: "Open pipeline", value: money(K.open_pipeline), note: `${K.open} deals still in progress` },
  ];
  $("kpis").innerHTML = kpis
    .map((k) => `<div class="card kpi"><div class="label">${k.label}</div><div class="value">${k.value}</div><div class="note">${k.note}</div></div>`)
    .join("");

  // ---------- takeaways ----------
  const ref = ch("Referral"), web = ch("Webinar"), ps = ch("Paid Social"), cs = ch("Content Syndication");
  const h = D.halves, h0 = h["2025 H1"], h2 = h["2026 H1"];
  const leadGrowth = Math.round((h2.leads / h0.leads - 1) * 100);
  const oppGrowth = Math.round((h2.opps / h0.opps - 1) * 100);
  const q0 = D.quarters[0], qN = D.quarters[D.quarters.length - 1];
  const lowLeads = ps.leads + cs.leads, lowRev = ps.revenue + cs.revenue, lowOpps = ps.opps + cs.opps;

  const takeaways = [
    {
      title: `Referrals are ${pct(ref.share_leads)} of leads but ${pct(ref.share_revenue, 0)} of revenue`,
      body: `Each referral lead is worth ${money(ref.rev_per_lead)} in closed-won revenue, about ${Math.round(ref.rev_per_lead / K.rev_per_lead)}× the average lead (${money(K.rev_per_lead)}). ` +
            `${pct(ref.lead_to_opp, 0)} of referral leads become opportunities, against ${pct(K.lead_to_opp, 0)} overall. That is an undercount: 3 of the 4 won deals with no amount recorded are referrals.`,
      so: `Referral is the most efficient channel we have and also the smallest. Customer and partner referral programs are where an extra dollar is most likely to pay off.`,
    },
    {
      title: `Leads grew ${leadGrowth}%, opportunities grew ${oppGrowth}%`,
      body: `Comparing H1 2026 with H1 2025: ${num(h0.leads)} → ${num(h2.leads)} leads, but only ${h0.opps} → ${h2.opps} opportunities. ` +
            `The lead-to-opportunity rate slid from ${pct(q0.lead_to_opp)} to ${pct(qN.lead_to_opp)}. Channel mix didn't cause it: the five weakest campaigns were a steady 24–30% of leads every quarter.`,
      so: `Lead volume is the wrong growth target. The next step is a review with Sales of MQL criteria and follow-up capacity.`,
    },
    {
      title: `Paid Social and Content Syndication: ${pct((lowLeads / K.leads) * 100, 0)} of leads, ${money(lowRev)} in revenue`,
      body: `${num(lowLeads)} leads produced ${lowOpps} opportunities and one closed deal. Under 3% of these leads become opportunities, against ${pct(K.lead_to_opp, 0)} for the company as a whole.`,
      so: `We don't have spend data, so ROI is unknown. Of everything here, this should be the first thing checked against budget. These channels may still help with awareness, but they aren't producing pipeline.`,
    },
    {
      title: `Webinars create pipeline but close at ${pct(web.win_rate, 0)}`,
      body: `Webinar leads become opportunities at an above-average rate (${pct(web.lead_to_opp, 0)}), but only ${web.won} of ${web.won + web.lost} closed deals were won, ` +
            `against a ${pct(K.win_rate, 0)} win rate company-wide. Referral, Organic Search, Events and Outbound all win at 43–47%.`,
      so: `Webinar leads may be getting passed to Sales before they're ready to buy. Check where those deals are lost.`,
    },
  ];
  $("takeaways").innerHTML = takeaways
    .map((t, i) => `<div class="card take"><div class="num">${i + 1}</div><div><h3>${t.title}</h3><p>${t.body}</p><p class="so"><b>So what:</b> ${t.so}</p></div></div>`)
    .join("");

  // ---------- funnel ----------
  const ramp = ["#86b6ef", "#5598e7", "#2a78d6", "#1c5cab", "#104281"]; // ordinal blue, light → dark
  const top = D.funnel[0].n;
  let fHtml = "";
  D.funnel.forEach((s, i) => {
    if (i > 0) {
      const prev = D.funnel[i - 1];
      const label = i === 4 ? `${pct((s.n / prev.n) * 100, 0)} of opportunities won (${pct(K.win_rate, 0)} of closed deals)` : `${pct((s.n / prev.n) * 100, 0)} converted`;
      fHtml += `<div class="funnel-row" style="padding:0"><div></div><div class="step">↓ ${label}</div><div></div></div>`;
    }
    fHtml += `<div class="funnel-row">
      <div class="stage">${s.stage}</div>
      <div class="bar-track"><div class="bar" style="width:${(s.n / top) * 100}%;background:${ramp[i]}"></div></div>
      <div class="count">${num(s.n)}<span>${pct((s.n / top) * 100)} of leads</span></div>
    </div>`;
  });
  $("funnel").innerHTML = fHtml;

  // ---------- Chart.js defaults ----------
  Chart.defaults.font.family = getComputedStyle(document.body).fontFamily;
  Chart.defaults.font.size = 12;
  Chart.defaults.color = "#7a7873";
  Chart.defaults.plugins.legend.display = false;
  Chart.defaults.plugins.tooltip.backgroundColor = "#0b0b0b";
  Chart.defaults.plugins.tooltip.padding = 10;
  Chart.defaults.plugins.tooltip.cornerRadius = 6;
  Chart.defaults.maintainAspectRatio = false;
  const grid = { color: "#e9e8e2", drawTicks: false };
  const noGrid = { display: false };
  const border = { color: "#c3c2b7" };

  // ---------- share of leads vs share of revenue ----------
  const chs = [...D.channels].sort((a, b) => b.share_revenue - a.share_revenue);
  new Chart($("shareChart"), {
    type: "bar",
    data: {
      labels: chs.map((c) => c.name),
      datasets: [
        { label: "Share of leads", data: chs.map((c) => c.share_leads), backgroundColor: "#b9b7ae", borderRadius: 4, borderSkipped: "start", barPercentage: 0.8, categoryPercentage: 0.7 },
        { label: "Share of closed-won revenue", data: chs.map((c) => c.share_revenue), backgroundColor: "#2a78d6", borderRadius: 4, borderSkipped: "start", barPercentage: 0.8, categoryPercentage: 0.7 },
      ],
    },
    options: {
      indexAxis: "y",
      scales: {
        x: { grid, border, ticks: { callback: (v) => v + "%", padding: 6, stepSize: 5, maxRotation: 0 }, max: 35 },
        y: { grid: noGrid, border, ticks: { color: "#0b0b0b", font: { size: 13 }, padding: 6 } },
      },
      plugins: {
        tooltip: {
          callbacks: {
            label: (ctx) => {
              const c = chs[ctx.dataIndex];
              return ctx.datasetIndex === 0
                ? ` Leads: ${pct(c.share_leads)} (${num(c.leads)})`
                : ` Revenue: ${pct(c.share_revenue)} (${money(c.revenue)})`;
            },
          },
        },
      },
    },
  });

  // ---------- tables ----------
  const flag = (v, avg) => (v == null ? "" : v >= avg * 1.25 ? "hi" : v <= avg * 0.75 ? "lo" : "");

  function scoreTable(rows, opts = {}) {
    const max = Math.max(...rows.map((r) => r.rev_per_lead));
    const head = `<thead><tr>
      <th>${opts.first || "Channel"}</th><th>Leads</th><th>MQL rate</th><th>Lead → opp</th><th>Win rate</th>
      <th>Closed-won revenue</th><th>Avg deal</th><th>Open pipeline</th><th style="min-width:150px">Revenue per lead</th></tr></thead>`;
    const body = rows.map((r) => `<tr>
      <td class="name">${r.name}${opts.sub ? `<span class="sub-name">${opts.sub(r)}</span>` : ""}</td>
      <td>${num(r.leads)}</td>
      <td class="${flag(r.mql_rate, K.mql_rate)}">${pct(r.mql_rate, 0)}</td>
      <td class="${flag(r.lead_to_opp, K.lead_to_opp)}">${pct(r.lead_to_opp)}</td>
      <td class="${flag(r.win_rate, K.win_rate)}" title="${r.won} won / ${r.lost} lost">${pct(r.win_rate, 0)}</td>
      <td>${money(r.revenue)}</td>
      <td>${money(r.avg_deal)}</td>
      <td>${money(r.open_pipeline)}</td>
      <td><span class="inbar"><span class="${flag(r.rev_per_lead, K.rev_per_lead)}">${money(r.rev_per_lead)}</span><span class="b" style="width:${Math.max(2, (r.rev_per_lead / max) * 80)}px"></span></span></td>
    </tr>`).join("");
    const foot = `<tr class="tfoot"><td>All leads</td><td>${num(K.leads)}</td><td>${pct(K.mql_rate, 0)}</td><td>${pct(K.lead_to_opp)}</td>
      <td>${pct(K.win_rate, 0)}</td><td>${money(K.revenue)}</td><td>${money(K.avg_deal)}</td><td>${money(K.open_pipeline)}</td><td>${money(K.rev_per_lead)}</td></tr>`;
    return head + `<tbody>${body}${foot}</tbody>`;
  }
  $("channelTable").innerHTML = scoreTable(D.channels);
  $("campaignTable").innerHTML = scoreTable(D.campaigns, { first: "Campaign", sub: (r) => r.channel });

  // ---------- trends ----------
  const qLabel = (q) => q.replace(/(\d{4})Q(\d)/, "Q$2 ’$1").replace(/’20/, "’");
  const qs = D.quarters.map((q) => qLabel(q.q));
  const smallOpts = (tickFmt, extra = {}) => ({
    scales: {
      x: { grid: noGrid, border, ticks: { padding: 4, maxRotation: 0, autoSkip: false, font: { size: 11 } } },
      y: { grid, border: { display: false }, beginAtZero: true, ticks: { callback: (v) => (typeof tickFmt === "function" ? tickFmt(v) : v), padding: 6, maxTicksLimit: 5 }, ...extra },
    },
  });
  new Chart($("leadsQ"), {
    type: "bar",
    data: { labels: qs, datasets: [{ data: D.quarters.map((q) => q.leads), backgroundColor: "#2a78d6", borderRadius: 4, borderSkipped: "start", maxBarThickness: 36 }] },
    options: { ...smallOpts((v) => v), plugins: { tooltip: { callbacks: { label: (c) => ` ${num(c.raw)} leads · ${D.quarters[c.dataIndex].opps} became opps` } } } },
  });
  new Chart($("convQ"), {
    type: "line",
    data: { labels: qs, datasets: [{ data: D.quarters.map((q) => q.lead_to_opp), borderColor: "#2a78d6", backgroundColor: "#2a78d6", borderWidth: 2, pointRadius: 4, pointHoverRadius: 6, pointBorderColor: "#fcfcfb", pointBorderWidth: 2, tension: 0 }] },
    options: { ...smallOpts((v) => v + "%", { max: 16 }), interaction: { mode: "index", intersect: false }, plugins: { tooltip: { callbacks: { label: (c) => ` ${pct(c.raw)} of leads became opportunities` } } } },
  });
  const rq = D.revenue_by_q;
  new Chart($("revQ"), {
    type: "bar",
    data: { labels: rq.map((r) => qLabel(r.q)), datasets: [{ data: rq.map((r) => r.revenue), backgroundColor: "#2a78d6", borderRadius: 4, borderSkipped: "start", maxBarThickness: 36 }] },
    options: { ...smallOpts((v) => money(v)), plugins: { tooltip: { callbacks: { label: (c) => ` ${money(c.raw)} from ${rq[c.dataIndex].deals} deals` } } } },
  });

  // ---------- segments ----------
  const segNames = Object.keys(D.segments);
  function segTable(name) {
    const rows = D.segments[name];
    const max = Math.max(...rows.map((r) => r.rev_per_lead));
    const head = `<thead><tr><th>${name}</th><th>Leads</th><th>Lead → opp</th><th>Win rate</th><th>Avg deal</th><th>Closed-won revenue</th><th style="min-width:150px">Revenue per lead</th></tr></thead>`;
    const body = rows.map((r) => `<tr>
      <td class="name">${r.name}</td><td>${num(r.leads)}</td>
      <td class="${flag(r.lead_to_opp, K.lead_to_opp)}">${pct(r.lead_to_opp)}</td>
      <td class="${flag(r.win_rate, K.win_rate)}" title="${r.won} won / ${r.lost} lost">${pct(r.win_rate, 0)}</td>
      <td>${money(r.avg_deal)}</td><td>${money(r.revenue)}</td>
      <td><span class="inbar"><span>${money(r.rev_per_lead)}</span><span class="b" style="width:${Math.max(2, (r.rev_per_lead / max) * 80)}px"></span></span></td>
    </tr>`).join("");
    $("segTable").innerHTML = head + `<tbody>${body}</tbody>`;
  }
  $("segTabs").innerHTML = segNames.map((n, i) => `<button role="tab" aria-selected="${i === 0}" data-seg="${n}">${n}</button>`).join("");
  $("segTabs").addEventListener("click", (e) => {
    const b = e.target.closest("button");
    if (!b) return;
    $("segTabs").querySelectorAll("button").forEach((x) => x.setAttribute("aria-selected", x === b));
    segTable(b.dataset.seg);
  });
  segTable(segNames[0]);

  // ---------- data notes ----------
  $("notes").innerHTML = D.quality
    .map((q) => `<div class="card note-item"><h3>${q.issue}${q.count != null ? `<span class="count">${num(q.count)} rows affected</span>` : ""}</h3>
      <div><p>${q.detail}</p><p class="action">${q.action}</p></div></div>`)
    .join("");
  $("amtTable").innerHTML =
    `<thead><tr><th>Opportunity</th><th>Company size</th><th>Amount in CRM</th><th>Corrected (÷100)</th><th>Typical deal for this size</th></tr></thead><tbody>` +
    D.corrected_amounts.map((r) => `<tr><td class="name">${r.opportunity_id}</td><td>${r.company_size}</td><td>${money(r.amount_raw)}</td><td>${money(r.deal_amount_usd)}</td><td>${money(r.size_median)}</td></tr>`).join("") +
    `<tr class="tfoot"><td colspan="2">Closed-won total</td><td>${money(D.raw_closed_won)}</td><td>${money(K.revenue)}</td><td></td></tr></tbody>`;
})();
