// Renders the dashboard from window.DATA (generated by scripts/clean.py).
// Every number on the page comes from DATA, so re-running the script updates the whole page.
// Tables and text render first; charts render last and only if Chart.js loaded,
// so a missing chart library can never blank the rest of the page.
(function () {
  const D = window.DATA;
  const K = D.kpis;
  const I = D.insights;
  const $ = (id) => document.getElementById(id);

  // ---------- formatting helpers ----------
  const num = (n) => n.toLocaleString("en-US");
  const money = (n) => {
    if (n == null) return "–";
    if (Math.abs(n) >= 1e6) return "$" + (n / 1e6).toFixed(2).replace(/\.?0+$/, "") + "M";
    if (Math.abs(n) >= 1e4) return "$" + Math.round(n / 1e3) + "K";
    return "$" + Math.round(n).toLocaleString("en-US");
  };
  const pct = (n, d = 1) => (n == null ? "–" : n.toFixed(d) + "%");
  const ch = (name) => D.channels.find((c) => c.name === name);
  const src = (name) => D.sources.find((s) => s.name === name);
  const list = (xs) => xs.slice(0, -1).join(", ") + " and " + xs[xs.length - 1];
  const qLabel = (q) => q.replace(/(\d{4})Q(\d)/, "Q$2 ’$1").replace(/’20/, "’");

  // ---------- header ----------
  $("header-sub").innerHTML =
    `${num(D.meta.rows_clean)} leads created ${D.meta.lead_start}–${D.meta.lead_end}, followed through to closed deals. ` +
    `The raw CRM export needed cleanup first: duplicates, inconsistent labels, and six deal amounts entered 100× too high. ` +
    `<a href="#data-notes">See what changed</a>.`;
  $("asof").innerHTML = [
    `Deal outcomes as of <b>${D.meta.last_close}</b>`,
    `Pipeline activity through <b>${D.meta.last_activity}</b>`,
    `Single-touch attribution (original campaign)`,
    `No spend data`,
  ].map((s) => `<li>${s}</li>`).join("");

  // ---------- KPI tiles ----------
  const mkt = src("Marketing programs");
  const P = D.pipeline;
  const kpis = [
    { label: "Leads created", value: num(K.leads), note: `${D.meta.lead_start} – ${D.meta.lead_end} · ${pct(K.mql_rate, 0)} became MQL` },
    { label: "Opportunities", value: num(K.opps), note: `${pct(K.lead_to_opp)} of leads · ${money(K.pipeline_created)} pipeline created` },
    { label: "Closed-won revenue", value: money(K.revenue), note: `${K.won} deals · avg ${money(K.avg_deal)} (${D.meta.priced_wins} with amounts)` },
    { label: "Win rate", value: pct(K.win_rate, 0), note: `${K.won} won / ${K.lost} lost · median ${D.meta.sales_cycle_median_days} days opp → close` },
    { label: "Revenue from marketing programs", value: pct(mkt.share_revenue, 0), note: `and ${pct(mkt.share_pipeline, 0)} of pipeline; the rest is referral and SDR` },
    { label: "Open pipeline", value: money(K.open_pipeline), note: `${K.open} open deals at export · ${money(P.open_at_cutoff_amount)} was open on ${D.meta.last_close}` },
  ];
  $("kpis").innerHTML = kpis
    .map((k) => `<div class="card kpi"><div class="label">${k.label}</div><div class="value">${k.value}</div><div class="note">${k.note}</div></div>`)
    .join("");

  // ---------- takeaways ----------
  const ref = ch("Referral"), R = I.referral, E = I.events, W = I.weak, PS = I.paid_search, G = I.growth;
  const h0 = D.halves["2025 H1"], h2 = D.halves["2026 H1"];
  const takeaways = [
    {
      title: `Referrals are ${pct(ref.share_leads)} of leads but ${pct(ref.share_revenue, 0)} of revenue`,
      body: `${pct(ref.lead_to_opp, 0)} of referral leads become opportunities, against ${pct(R.lead_to_opp_rest, 0)} of all other leads. ` +
            `Each referral lead is worth ${money(ref.rev_per_lead)} in closed-won revenue, about ${R.rev_per_lead_multiple}× the average lead. ` +
            `The edge is in conversion, not closing: referral deals win ${pct(ref.win_rate, 0)} of the time against ${pct(R.win_rate_rest, 0)} for everything else, a gap chance could explain. ` +
            `Revenue is also understated: ${R.unpriced_wins} of the ${R.unpriced_wins_total} won deals with no amount recorded are referrals.`,
      so: `Referral is the highest-yield source per lead. Whether it's the best place for the next dollar depends on what the program costs, which this export doesn't include, and on how many more referrals customers and partners can realistically produce.`,
    },
    {
      title: `Events turn leads into opportunities at twice the usual rate`,
      body: `Events are ${pct(E.share_leads)} of leads and ${pct(E.share_revenue, 0)} of revenue. ${pct(E.lead_to_opp)} of event leads become opportunities, against ${pct(E.lead_to_opp_rest)} for all other leads, ` +
            `and that holds for all ${E.programs} event programs (${E.program_lead_to_opp_range[0]}–${pct(E.program_lead_to_opp_range[1])}). ` +
            `They produce ${E.won_per_100.toFixed(1)} won deals per 100 leads, against ${E.won_per_100_rest.toFixed(1)} elsewhere. ` +
            `As with referrals, the edge is in conversion: the ${pct(E.win_rate, 0)} win rate isn't reliably higher than the ${pct(E.win_rate_rest, 0)} elsewhere.`,
      so: `Events are the strongest source marketing fully controls. They usually cost more per lead than digital channels, so the case for more of them rests on cost per opportunity: the first number to pull once spend data is available.`,
    },
    {
      title: `${list(W.channels)}: ${pct(W.share_leads, 0)} of leads, ${W.won} won deal`,
      body: `${num(W.leads)} leads produced ${W.opps} opportunities (${pct(W.lead_to_opp)}, against ${pct(W.lead_to_opp_rest)} for every other source) and ${W.won} won deal worth ${money(W.revenue)}. ` +
            `The leads drop out early: ${pct(W.mql_rate, 0)} become MQLs, against ${pct(W.mql_rate_rest, 0)} elsewhere. ` +
            `They do hold ${money(W.open_pipeline)} of open pipeline, ${money(W.largest_open)} of it a single ${W.largest_open_campaign} deal.`,
      so: `There's no spend data, so ROI is unknown, but these channels are the first thing to check against budget. If they're meant to build awareness, judge them on that; as pipeline sources, they aren't working.`,
    },
    {
      title: `Leads grew ${G.lead_growth}%; opportunities from those leads grew ${G.opp_growth}%`,
      body: `Leads created in H1 2026 vs H1 2025: ${num(h0.leads)} → ${num(h2.leads)}, and their opportunities ${h0.opps} → ${h2.opps}. ` +
            `Lead → opportunity was ${pct(h0.lead_to_opp)} in H1 2025 and has held at ${G.later_quarters_range[0]}–${pct(G.later_quarters_range[1])} every quarter since. ` +
            `Channel mix didn't cause it: at H1 2025's channel rates, H1 2026's leads would have converted at ${pct(G.mix_expected)}. ` +
            `The MQL rate didn't move (${pct(h0.mql_rate, 0)} → ${pct(h2.mql_rate, 0)}); the softening is after MQL, in SQL acceptance and SQL → opportunity. ` +
            `The gap is modest and statistically borderline (p = ${G.p.toFixed(2)}), so treat it as a signal to check, not a proven decline.`,
      so: `More leads hasn't meant proportionally more pipeline. Before setting the next lead-volume target, review the MQL → SQL handoff and SDR follow-up with Sales.`,
    },
  ];
  $("takeaways").innerHTML = takeaways
    .map((t, i) => `<div class="card take"><div class="num">${i + 1}</div><div><h3>${t.title}</h3><p>${t.body}</p><p class="so"><b>So what:</b> ${t.so}</p></div></div>`)
    .join("");

  const N = I.not_solid, T = N.tests;
  const web = ch("Webinar");
  const caveats = [
    `<b>Webinar win rate.</b> Only ${N.webinar_won} of ${N.webinar_closed} closed webinar deals were won (${pct(web.win_rate, 0)}). But webinar leads from H2 2025 went ${N.webinar_h2_won} for ${N.webinar_h2_closed}; every other period won ${pct(N.webinar_other_win_rate, 0)}, against ${pct(N.rest_other_win_rate, 0)} for other channels over the same periods. One bad batch, not a channel trait. Worth a deal review, not a budget decision.`,
    `<b>Paid Search, the largest lead source.</b> It supplies ${pct(PS.share_leads, 0)} of leads and wins ${PS.won_per_100.toFixed(1)} deals per 100 of them, against ${PS.won_per_100_rest.toFixed(1)} for all other leads, a gap chance could explain (p = ${PS.won_per_100_p.toFixed(2)}). ` +
      `Its #${PS.revenue_rank} revenue rank rests on ${PS.corrected_deals} of the six corrected deals; without them it would rank #${PS.revenue_rank_if_excluded}. ` +
      `On revenue, ${list(PS.close_call_channels)} sit within ${money(PS.close_call_spread)} of each other and can't be ranked. Worth a campaign-level review once spend is known.`,
    `<b>Region and industry.</b> Neither shows a difference in conversion or win rate bigger than chance (p ≥ ${Math.min(T.region_lead_to_opp, T.region_win_rate, T.industry_lead_to_opp, T.industry_win_rate).toFixed(2)}). Company size matters for deal size, not for whether a deal is won (p = ${T.company_size_win_rate.toFixed(2)}).`,
    `<b>Sales reps.</b> Win rates across the ${N.reps} reps range from ${N.rep_win_rate_range[0]}% to ${N.rep_win_rate_range[1]}%, which is within what chance produces on ${N.rep_closed_range[0]}–${N.rep_closed_range[1]} closed deals each (p = ${T.owner_win_rate.toFixed(2)}).`,
  ];
  $("caveats").innerHTML = caveats.map((c) => `<li>${c}</li>`).join("");

  // ---------- source split ----------
  const srcColor = ["var(--src-1)", "var(--src-2)", "var(--src-3)"];
  const srcInk = ["#fff", "var(--ink)", "var(--ink)"];
  const ref2 = src("Customer & partner referral");
  $("sources-sub").innerHTML =
    `Marketing programs bring ${pct(mkt.share_leads, 0)} of leads but ${pct(mkt.share_revenue, 0)} of closed-won revenue. ` +
    `Customer and partner referrals bring ${pct(ref2.share_leads)} of leads and ${pct(ref2.share_revenue, 0)} of revenue. ` +
    `Counting referrals separately is a judgment call: referral programs are often run by marketing, but the lead comes from a customer or partner.`;
  $("sources-legend").innerHTML = D.sources.map((s, i) => `<span><i style="background:${srcColor[i]}"></i>${s.name}</span>`).join("");
  const stackRows = [
    { what: "Leads", sub: num(K.leads), key: "share_leads" },
    { what: "Pipeline created", sub: money(K.pipeline_created), key: "share_pipeline" },
    { what: "Closed-won revenue", sub: money(K.revenue), key: "share_revenue" },
  ];
  $("sources-stack").innerHTML = stackRows
    .map((r) => `<div class="stack-row"><div class="what">${r.what}<span>${r.sub}</span></div><div class="stack" role="img" aria-label="${r.what} by source: ${D.sources.map((s) => `${s.name} ${pct(s[r.key], 0)}`).join(", ")}">` +
      D.sources.map((s, i) => `<div class="seg" style="flex:${s[r.key]};background:${srcColor[i]};color:${srcInk[i]}" title="${s.name}: ${pct(s[r.key])}">${s[r.key] >= 9 ? pct(s[r.key], 0) : ""}</div>`).join("") +
      `</div></div>`)
    .join("");
  $("sourcesTable").innerHTML =
    `<thead><tr><th>Source</th><th>Leads</th><th>Lead → opp</th><th class="wide-only">Pipeline created</th><th>Closed-won revenue</th><th class="wide-only">Won per 100 leads</th><th>Revenue per lead</th></tr></thead><tbody>` +
    D.sources.map((s, i) => `<tr><td class="name"><span class="dot" style="background:${srcColor[i]}"></span>${s.name}</td><td>${num(s.leads)}</td><td>${pct(s.lead_to_opp)}</td>` +
      `<td class="wide-only">${money(s.pipeline_created)}</td><td>${money(s.revenue)}</td><td class="wide-only">${s.won_per_100.toFixed(1)}</td><td>${money(s.rev_per_lead)}</td></tr>`).join("") +
    `<tr class="tfoot"><td>All leads</td><td>${num(K.leads)}</td><td>${pct(K.lead_to_opp)}</td><td class="wide-only">${money(K.pipeline_created)}</td><td>${money(K.revenue)}</td><td class="wide-only">${K.won_per_100.toFixed(1)}</td><td>${money(K.rev_per_lead)}</td></tr></tbody>`;

  // ---------- funnel ----------
  const stalled = D.quality.find((q) => q.issue === "No outcome for leads that stall");
  $("funnel-sub").innerHTML =
    `Every lead created in the period, and how far it got. Percentages under each bar are stage-to-stage conversion. ` +
    `${num(stalled.count)} leads stopped at MQL or SQL and have no rejected or recycled status in the CRM.`;
  const ramp = ["#86b6ef", "#5598e7", "#2a78d6", "#1c5cab", "#104281"]; // ordinal blue, light → dark
  const top = D.funnel[0].n;
  let fHtml = "";
  D.funnel.forEach((s, i) => {
    if (i > 0) {
      const prev = D.funnel[i - 1];
      const label = i === D.funnel.length - 1
        ? `${pct((s.n / prev.n) * 100, 0)} of opportunities won so far (${pct(K.win_rate, 0)} of closed deals)`
        : `${pct((s.n / prev.n) * 100, 0)} converted`;
      fHtml += `<div class="funnel-row" style="padding:0"><div></div><div class="step">↓ ${label}</div><div></div></div>`;
    }
    fHtml += `<div class="funnel-row">
      <div class="stage">${s.stage}</div>
      <div class="bar-track"><div class="bar" style="width:${(s.n / top) * 100}%;background:${ramp[i]}"></div></div>
      <div class="count">${num(s.n)}<span>${i === 0 ? "all leads" : pct((s.n / top) * 100) + " of leads"}</span></div>
    </div>`;
  });
  $("funnel").innerHTML = fHtml;

  // ---------- tables ----------
  const cell = (r, key, text) => {
    const f = r.flags && r.flags[key];
    const t = f ? ` title="${f === "hi" ? "Significantly above" : "Significantly below"} all other leads"` : "";
    return `<span class="${f || ""}"${t}>${text}</span>`;
  };
  const winCell = (r) => `${cell(r, "win_rate", pct(r.win_rate, 0))}<span class="n">${r.won}/${r.won + r.lost}</span>`;

  function scoreTable(rows, opts = {}) {
    const max = Math.max(...rows.map((r) => r.rev_per_lead));
    const head = `<thead><tr>
      <th>${opts.first || "Channel"}</th><th>Leads</th><th class="wide-only">MQL rate</th><th>Lead → opp</th><th>Won per 100 leads</th><th>Win rate</th>
      <th>Closed-won revenue</th><th class="wide-only">Avg deal</th><th class="wide-only">Open pipeline</th><th style="min-width:150px">Revenue per lead</th></tr></thead>`;
    const body = rows.map((r) => `<tr>
      <td class="name">${r.name}${opts.sub ? `<span class="sub-name">${opts.sub(r)}</span>` : ""}</td>
      <td>${num(r.leads)}</td>
      <td class="wide-only">${cell(r, "mql_rate", pct(r.mql_rate, 0))}</td>
      <td>${cell(r, "lead_to_opp", pct(r.lead_to_opp))}</td>
      <td>${cell(r, "won_per_100", r.won_per_100.toFixed(1))}</td>
      <td>${winCell(r)}</td>
      <td>${money(r.revenue)}</td>
      <td class="wide-only">${money(r.avg_deal)}</td>
      <td class="wide-only">${money(r.open_pipeline)}</td>
      <td><span class="inbar"><span>${money(r.rev_per_lead)}</span><span class="b" style="width:${Math.max(2, (r.rev_per_lead / max) * 80)}px"></span></span></td>
    </tr>`).join("");
    const foot = `<tr class="tfoot"><td>All leads</td><td>${num(K.leads)}</td><td class="wide-only">${pct(K.mql_rate, 0)}</td><td>${pct(K.lead_to_opp)}</td><td>${K.won_per_100.toFixed(1)}</td>
      <td>${pct(K.win_rate, 0)}<span class="n">${K.won}/${K.won + K.lost}</span></td><td>${money(K.revenue)}</td><td class="wide-only">${money(K.avg_deal)}</td><td class="wide-only">${money(K.open_pipeline)}</td><td>${money(K.rev_per_lead)}</td></tr>`;
    return head + `<tbody>${body}${foot}</tbody>`;
  }
  const sourceTag = (name) => (name === "Marketing programs" ? "" : name);
  $("channelTable").innerHTML = scoreTable(D.channels, { sub: (r) => sourceTag(r.source) });
  $("campaign-summary").textContent = `Show all ${D.campaigns.length} campaigns`;
  $("campaignTable").innerHTML = scoreTable(D.campaigns, { first: "Campaign", sub: (r) => r.channel });

  // ---------- segments ----------
  const segCaptions = {
    "Company size": "Bigger companies buy much bigger deals, but they don't win more often. Mid-to-large companies (1001–5000) convert to opportunities a little more often.",
    Region: "No regional difference in conversion or win rate is bigger than chance would produce. Shown for completeness.",
    Industry: "No industry difference in conversion or win rate is bigger than chance would produce. Shown for completeness.",
  };
  const segNames = Object.keys(D.segments);
  function segTable(name) {
    const rows = D.segments[name];
    const max = Math.max(...rows.map((r) => r.rev_per_lead));
    $("segCaption").textContent = segCaptions[name] || "";
    const head = `<thead><tr><th>${name}</th><th>Leads</th><th>Lead → opp</th><th>Win rate</th><th>Avg deal</th><th>Closed-won revenue</th><th style="min-width:150px">Revenue per lead</th></tr></thead>`;
    const body = rows.map((r) => `<tr>
      <td class="name">${r.name}</td><td>${num(r.leads)}</td>
      <td>${cell(r, "lead_to_opp", pct(r.lead_to_opp))}</td>
      <td>${winCell(r)}</td>
      <td>${money(r.avg_deal)}</td><td>${money(r.revenue)}</td>
      <td><span class="inbar"><span>${money(r.rev_per_lead)}</span><span class="b" style="width:${Math.max(2, (r.rev_per_lead / max) * 80)}px"></span></span></td>
    </tr>`).join("");
    $("segTable").innerHTML = head + `<tbody>${body}</tbody>`;
  }
  $("segTabs").innerHTML = segNames.map((n, i) => `<button type="button" aria-pressed="${i === 0}" data-seg="${n}">${n}</button>`).join("");
  $("segTabs").addEventListener("click", (e) => {
    const b = e.target.closest("button");
    if (!b) return;
    $("segTabs").querySelectorAll("button").forEach((x) => x.setAttribute("aria-pressed", x === b));
    segTable(b.dataset.seg);
  });
  segTable(segNames[0]);

  // ---------- trend + pipeline notes ----------
  const partial = D.revenue_by_q.filter((r) => r.partial).map((r) => qLabel(r.q));
  $("trend-note").innerHTML =
    `${list(partial)} revenue is incomplete: the export only contains leads created from ${D.meta.lead_start}, so deals from earlier leads that closed in those quarters are missing. ` +
    `The opportunity-rate trend is safe to read: every opportunity appears within ${D.meta.max_lead_to_opp_days} days of its lead, and opportunities are recorded through ${D.meta.last_activity}. ` +
    `Quarter-to-quarter differences under about 3 points are within noise. ` +
    `Open pipeline: ${P.past_due_at_last_activity_deals} deals (${money(P.past_due_at_last_activity_amount)}) were expected to close by ${D.meta.last_activity} but hadn't, and no deal at all closed after ${D.meta.last_close}. ` +
    `Treat the expected close dates as forecasts to confirm with Sales.`;
  $("share-note").innerHTML =
    `Only the ends of this ranking are solid: Referral at the top, Paid Social and Content Syndication at the bottom. ` +
    `${list(PS.close_call_channels)} are within ${money(PS.close_call_spread)} of each other. ` +
    `Paid Search's place depends on how the six corrected deal amounts are handled (#${PS.revenue_rank} as corrected, #${PS.revenue_rank_if_excluded} if they're left out).`;

  // ---------- data notes ----------
  $("notes").innerHTML = D.quality
    .map((q) => `<div class="card note-item"><h3>${q.issue}${q.count != null ? `<span class="count">${num(q.count)} ${q.count === 1 ? "row" : "rows"} affected</span>` : ""}</h3>
      <div><p>${q.detail}</p><p class="action">${q.action}</p></div></div>`)
    .join("");
  $("amtTable").innerHTML =
    `<thead><tr><th>Opportunity</th><th>Company size</th><th>Amount in CRM</th><th>Corrected (÷100)</th><th>Median won deal, same size</th></tr></thead><tbody>` +
    D.corrected_amounts.map((r) => `<tr><td class="name">${r.opportunity_id}</td><td>${r.company_size}</td><td>${money(r.amount_raw)}</td><td>${money(r.deal_amount_usd)}</td><td>${money(r.won_median)}</td></tr>`).join("") +
    `<tr class="tfoot"><td colspan="2">Closed-won total</td><td>${money(D.raw_closed_won)}</td><td>${money(K.revenue)}</td><td></td></tr></tbody>`;

  // ---------- charts (last, so nothing above depends on Chart.js) ----------
  if (!window.Chart) {
    document.querySelectorAll("canvas").forEach((c) => {
      c.insertAdjacentHTML("afterend", `<div class="chart-fallback">Chart unavailable: the chart library didn't load. The tables on this page carry the same numbers.</div>`);
    });
    return;
  }
  Chart.defaults.font.family = getComputedStyle(document.body).fontFamily;
  Chart.defaults.font.size = 12;
  Chart.defaults.color = "#6b6964";
  Chart.defaults.plugins.legend.display = false;
  Chart.defaults.plugins.tooltip.backgroundColor = "#0b0b0b";
  Chart.defaults.plugins.tooltip.padding = 10;
  Chart.defaults.plugins.tooltip.cornerRadius = 6;
  Chart.defaults.maintainAspectRatio = false;
  const grid = { color: "#e9e8e2", drawTicks: false };
  const noGrid = { display: false };
  const border = { color: "#c3c2b7" };
  const niceMax = (v, step) => Math.ceil((v * 1.1) / step) * step;

  // share of leads vs share of revenue
  const chs = [...D.channels].sort((a, b) => b.share_revenue - a.share_revenue);
  const shareMax = niceMax(Math.max(...chs.map((c) => Math.max(c.share_leads, c.share_revenue))), 5);
  new Chart($("shareChart"), {
    type: "bar",
    data: {
      labels: chs.map((c) => c.name),
      datasets: [
        { label: "Share of leads", data: chs.map((c) => c.share_leads), backgroundColor: "#8a887f", borderRadius: 4, borderSkipped: "start", barPercentage: 0.8, categoryPercentage: 0.7 },
        { label: "Share of closed-won revenue", data: chs.map((c) => c.share_revenue), backgroundColor: "#2a78d6", borderRadius: 4, borderSkipped: "start", barPercentage: 0.8, categoryPercentage: 0.7 },
      ],
    },
    options: {
      indexAxis: "y",
      scales: {
        x: { grid, border, ticks: { callback: (v) => v + "%", padding: 6, stepSize: 5, maxRotation: 0 }, max: shareMax },
        y: { grid: noGrid, border, ticks: { color: "#0b0b0b", font: { size: 13 }, padding: 6 } },
      },
      plugins: {
        tooltip: {
          callbacks: {
            label: (ctx) => {
              const c = chs[ctx.dataIndex];
              return ctx.datasetIndex === 0
                ? ` Leads: ${pct(c.share_leads)} (${num(c.leads)})`
                : ` Revenue: ${pct(c.share_revenue)} (${money(c.revenue)})`;
            },
          },
        },
      },
    },
  });

  const smallOpts = (tickFmt, extra = {}) => ({
    scales: {
      x: { grid: noGrid, border, ticks: { padding: 4, maxRotation: 0, autoSkip: false, font: { size: 11 } } },
      y: { grid, border: { display: false }, beginAtZero: true, ticks: { callback: tickFmt, padding: 6, maxTicksLimit: 5 }, ...extra },
    },
  });
  const qs = D.quarters.map((q) => qLabel(q.q));
  new Chart($("leadsQ"), {
    type: "bar",
    data: { labels: qs, datasets: [{ data: D.quarters.map((q) => q.leads), backgroundColor: "#2a78d6", borderRadius: 4, borderSkipped: "start", maxBarThickness: 36 }] },
    options: { ...smallOpts((v) => num(v)), plugins: { tooltip: { callbacks: { label: (c) => ` ${num(c.raw)} leads · ${D.quarters[c.dataIndex].opps} became opportunities` } } } },
  });
  const rateMax = niceMax(Math.max(...D.quarters.map((q) => q.lead_to_opp)), 2);
  new Chart($("convQ"), {
    type: "line",
    data: { labels: qs, datasets: [{ data: D.quarters.map((q) => q.lead_to_opp), borderColor: "#2a78d6", backgroundColor: "#2a78d6", borderWidth: 2, pointRadius: 4, pointHoverRadius: 6, pointBorderColor: "#fcfcfb", pointBorderWidth: 2, tension: 0 }] },
    options: { ...smallOpts((v) => v + "%", { max: rateMax }), interaction: { mode: "index", intersect: false }, plugins: { tooltip: { callbacks: { label: (c) => ` ${pct(c.raw)} of leads became opportunities (${D.quarters[c.dataIndex].opps} of ${num(D.quarters[c.dataIndex].leads)})` } } } },
  });
  const rq = D.revenue_by_q;
  new Chart($("revQ"), {
    type: "bar",
    data: {
      labels: rq.map((r) => qLabel(r.q) + (r.partial ? "*" : "")),
      datasets: [{ data: rq.map((r) => r.revenue), backgroundColor: rq.map((r) => (r.partial ? "#b7d3f6" : "#2a78d6")), borderRadius: 4, borderSkipped: "start", maxBarThickness: 36 }],
    },
    options: {
      ...smallOpts((v) => money(v)),
      plugins: { tooltip: { callbacks: { label: (c) => ` ${money(c.raw)} from ${rq[c.dataIndex].deals} deals${rq[c.dataIndex].partial ? " (partial quarter)" : ""}` } } },
    },
  });
  const pm = P.by_month;
  new Chart($("pipeM"), {
    type: "bar",
    data: { labels: pm.map((m) => m.month.replace(/ (\d{2})(\d{2})$/, " ’$2")), datasets: [{ data: pm.map((m) => m.amount), backgroundColor: "#2a78d6", borderRadius: 4, borderSkipped: "start", maxBarThickness: 36 }] },
    options: { ...smallOpts((v) => money(v)), plugins: { tooltip: { callbacks: { label: (c) => ` ${money(c.raw)} across ${pm[c.dataIndex].deals} deals` } } } },
  });
})();
